# Generated by Django 3.2.7 on 2021-09-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lordoftherings', '0002_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
