# Generated by Django 3.2.7 on 2021-09-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lordoftherings', '0004_auto_20210915_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='slug',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='slug',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='slug',
            new_name='_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='academyAwardNominations',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='academyAwardWins',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='boxOfficeRevenueInMillions',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rottenTomatoesScore',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtimeInMunutes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
