# Generated by Django 3.2.7 on 2021-09-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lordoftherings', '0005_auto_20210916_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='runtimeInMunutes',
            new_name='runtimeInMinutes',
        ),
    ]
