# Generated by Django 3.2.7 on 2021-09-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lordoftherings', '0006_rename_runtimeinmunutes_movie_runtimeinminutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='budgetInMillions',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
