# Generated by Django 3.2.7 on 2021-09-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lordoftherings', '0009_alter_character_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='character',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='quote',
        ),
    ]
