# Generated by Django 3.2.7 on 2021-09-16 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lordoftherings', '0010_auto_20210916_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lordoftherings.character'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lordoftherings.quote'),
        ),
    ]
